# Generated by Django 5.0.4 on 2024-05-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0002_administrateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='slugEdituer',
            new_name='slugAdministrateur',
        ),
    ]
