# Generated by Django 5.0.4 on 2024-05-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0003_rename_slugedituer_administrateur_slugadministrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('No Active\t', 'No Active')], max_length=50, null=True),
        ),
    ]
