# Generated by Django 5.0.4 on 2024-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0004_administrateur_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='Status',
            field=models.CharField(default='Active', max_length=50, null=True),
        ),
    ]
