# Generated by Django 5.0.4 on 2024-05-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0005_alter_administrateur_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
