# Generated by Django 5.0.4 on 2024-05-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0006_cliente_solde'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slugCliente',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
