# Generated by Django 5.0.4 on 2024-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0009_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='solde',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='solde',
            field=models.IntegerField(default=0),
        ),
    ]
