# Generated by Django 5.0.4 on 2024-05-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0012_alter_websites_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='Builder',
            field=models.CharField(default='Not yet', max_length=50, null=True),
        ),
    ]
