# Generated by Django 5.0.4 on 2024-05-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0013_achat_builder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achat',
            new_name='AchatWebsites',
        ),
    ]
