# Generated by Django 5.0.4 on 2024-05-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0014_rename_achat_achatwebsites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
