# Generated by Django 5.0.4 on 2024-05-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0015_alter_cliente_solde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='cliente',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
