# Generated by Django 5.0.4 on 2024-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0019_alter_cliente_code_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='code_Website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
