# Generated by Django 5.0.4 on 2024-05-07 16:28

import websitebuilder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0020_websites_code_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='code_Website',
            field=models.CharField(default=websitebuilder.models.generate_cliente_code, max_length=100, null=True),
        ),
    ]
