# Generated by Django 5.0.4 on 2024-05-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0021_alter_websites_code_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='websites',
            name='code_Website',
        ),
        migrations.AddField(
            model_name='websites',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('No Active', 'No Active')], default='Active', max_length=50, null=True),
        ),
    ]
