# Generated by Django 5.0.4 on 2024-05-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0022_remove_websites_status_remove_websites_code_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatwebsites',
            name='Builder',
            field=models.CharField(choices=[('Builder', 'Builder'), ('Not yet\t', 'Not yet')], default='Not yet', max_length=50, null=True),
        ),
    ]
