# Generated by Django 5.0.4 on 2024-05-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0024_rename_builder_achatwebsites_builderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatwebsites',
            name='BuilderStatus',
            field=models.CharField(choices=[('Builder', 'Builder'), ('Not yet', 'Not yet')], default='Not yet', max_length=50, null=True),
        ),
    ]
