# Generated by Django 5.0.4 on 2024-05-08 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0027_rename_slugsupports_supports_slugsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('No Active', 'No Active')], default='No Active', max_length=50, null=True)),
                ('StatusConsomé', models.CharField(choices=[('Consomé', 'Consomé'), ('Not Consomé', 'Not Consomé')], default='No Active', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.supports')),
            ],
        ),
    ]
