# Generated by Django 5.0.4 on 2024-05-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0028_achatsupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatsupport',
            name='StatusConsomé',
            field=models.CharField(choices=[('Consomé', 'Consomé'), ('Not Consomé', 'Not Consomé')], default='Not Consomé', max_length=50, null=True),
        ),
    ]
