# Generated by Django 5.0.4 on 2024-05-08 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0030_demandesupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandesupport',
            name='support',
        ),
        migrations.AddField(
            model_name='demandesupport',
            name='achatSupport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.achatsupport'),
            preserve_default=False,
        ),
    ]
