# Generated by Django 5.0.4 on 2024-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0034_demandesupport_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandesupport',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done yet', 'Not Done yet')], default='Not Done yet', max_length=50, null=True),
        ),
    ]
