# Generated by Django 5.0.4 on 2024-05-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0036_supporttechnique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatsupport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitebuilder.supporttechnique'),
        ),
        migrations.AlterField(
            model_name='demandesupport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitebuilder.supporttechnique'),
        ),
    ]
