# Generated by Django 5.0.4 on 2024-05-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0038_gestionnairecomptes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitebuilder.gestionnairecomptes'),
        ),
    ]
