# Generated by Django 5.0.4 on 2024-05-10 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0039_cliente_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRecharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Not Done yet', 'Not Done yet')], default='Not Done yet', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('code_DemandeRecharger', models.CharField(max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitebuilder.gestionnairecomptes')),
            ],
        ),
    ]
