# Generated by Django 5.0.4 on 2024-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0040_demanderecharger'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderecharger',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='demanderecharger',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
