# Generated by Django 5.0.4 on 2024-05-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0042_latracdemanderecharger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaTracDemandeRecharger',
            new_name='LaTraceDemandeRecharger',
        ),
    ]
