# Generated by Django 5.0.4 on 2024-05-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0043_rename_latracdemanderecharger_latracedemanderecharger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanderecharger',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done yet', 'Not Done yet'), ('inacceptable', 'inacceptable')], default='Not Done yet', max_length=50, null=True),
        ),
    ]
