# Generated by Django 5.0.4 on 2024-05-14 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0044_alter_demanderecharger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='latracedemanderecharger',
            name='demande_recharger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.demanderecharger'),
            preserve_default=False,
        ),
    ]
