# Generated by Django 5.0.4 on 2024-05-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0045_latracedemanderecharger_demande_recharger'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaTraceInacceptableDemandeRecharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('motifNonAcceptation', models.CharField(max_length=100, null=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('demande_recharger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.demanderecharger')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitebuilder.gestionnairecomptes')),
            ],
        ),
    ]
