# Generated by Django 5.0.4 on 2024-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0046_latraceinacceptabledemanderecharger'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderecharger',
            name='motifNonAcceptation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='LaTraceInacceptableDemandeRecharger',
        ),
    ]
