# Generated by Django 5.0.4 on 2024-05-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0047_demanderecharger_motifnonacceptation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AchatWebsites',
        ),
    ]
