# Generated by Django 5.0.4 on 2024-05-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0049_achatwebsites'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_port', models.CharField(blank=True, max_length=30, null=True)),
                ('app_port', models.CharField(blank=True, max_length=30, null=True)),
                ('nameWebsite', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('achat_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.achatwebsites')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
            ],
        ),
    ]
