# Generated by Django 5.0.4 on 2024-05-21 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0050_websitebuilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitebuilder',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites'),
        ),
    ]
