# Generated by Django 5.0.4 on 2024-05-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0051_websitebuilder_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitebuilder',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites'),
            preserve_default=False,
        ),
    ]
