# Generated by Django 5.0.4 on 2024-05-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0053_alter_achatwebsites_builderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationWebsites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('BuilderStatus', models.CharField(choices=[('Builder', 'Builder'), ('in progress', 'in progress'), ('Not yet', 'Not yet')], default='Not yet', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('websites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites')),
            ],
        ),
    ]
