# Generated by Django 5.0.4 on 2024-05-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0055_locationwebsitebuilder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedWebsiteBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_port', models.CharField(blank=True, max_length=30, null=True)),
                ('app_port', models.CharField(blank=True, max_length=30, null=True)),
                ('nameWebsite', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('location_website_builder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.locationwebsitebuilder')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites')),
                ('website_builder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websitebuilder')),
            ],
        ),
    ]
