# Generated by Django 5.0.4 on 2024-05-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0056_mergedwebsitebuilder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedwebsitebuilder',
            name='nameWebsite',
        ),
    ]
