# Generated by Django 5.0.4 on 2024-05-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0059_websitebuilder_date_debut_websitebuilder_date_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitebuilder',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='websitebuilder',
            name='date_fin',
        ),
    ]
