# Generated by Django 5.0.4 on 2024-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0060_remove_websitebuilder_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achatwebsites',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achatwebsites',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
