# Generated by Django 5.0.4 on 2024-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0061_achatwebsites_date_debut_achatwebsites_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nom_entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_ice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
