# Generated by Django 5.0.4 on 2024-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0062_cliente_address_cliente_nom_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedwebsitebuilder',
            name='Statu_du_website',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=50, null=True),
        ),
    ]
