# Generated by Django 5.0.4 on 2024-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0065_websites_location_payment_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites_location_payment_delay',
            name='Statu_du_website',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=50, null=True),
        ),
    ]
