# Generated by Django 5.0.4 on 2024-06-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0067_websites_client_statu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergedwebsitebuilder',
            name='Statu_du_website',
        ),
        migrations.RemoveField(
            model_name='mergedwebsitebuilder',
            name='Website_Client_statu',
        ),
    ]
