# Generated by Django 5.0.4 on 2024-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0068_remove_mergedwebsitebuilder_statu_du_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationwebsitebuilder',
            name='Statu_du_website',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='locationwebsitebuilder',
            name='Statu_du_website_action',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websitebuilder',
            name='Statu_du_website',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='websitebuilder',
            name='Statu_du_website_action',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=50, null=True),
        ),
    ]
