# Generated by Django 5.0.4 on 2024-06-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0070_website_need_reprendre_website_need_resiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationwebsitebuilder',
            name='Statu_du_website',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], default='1', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Website_need_suspendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statu_du_website', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('location_website_builder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.locationwebsitebuilder')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites')),
                ('website_builder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websitebuilder')),
            ],
        ),
    ]
