# Generated by Django 5.0.4 on 2024-06-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0073_rename_website_need_reprendre_website_resiliation_reprendre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website_resiliation_reprendre',
            new_name='Website_reprendre_resiliation',
        ),
    ]
