# Generated by Django 5.0.4 on 2024-06-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0075_website_need_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='prix_loyer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
