# Generated by Django 5.0.4 on 2024-06-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0076_websites_prix_loyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites_need_delete',
            name='website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websitebuilder'),
        ),
    ]
