# Generated by Django 5.0.4 on 2024-06-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0077_websites_need_delete_website_builder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites_need_delete',
            name='website',
        ),
    ]
