# Generated by Django 5.0.4 on 2024-06-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0078_remove_websites_need_delete_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationwebsitebuilder',
            name='Statu_du_website',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=50, null=True),
        ),
    ]
