# Generated by Django 5.0.4 on 2024-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0081_alter_locationwebsitebuilder_statu_du_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='CMS',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='catégorie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='websites',
            name='langues',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='plan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
