# Generated by Django 5.0.4 on 2024-06-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0082_websites_cms_websites_catégorie_websites_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
