# Generated by Django 5.0.4 on 2024-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0083_alter_websites_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achatsupport',
            old_name='solde',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='achatwebsites',
            old_name='solde',
            new_name='prix_achat',
        ),
        migrations.RenameField(
            model_name='locationwebsites',
            old_name='solde',
            new_name='prix_loyer',
        ),
        migrations.RemoveField(
            model_name='achatwebsites',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='achatwebsites',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='locationwebsites',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='locationwebsites',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='websitebuilder',
            name='Statu_du_website_action',
        ),
        migrations.AlterField(
            model_name='supports',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
