# Generated by Django 5.0.4 on 2024-06-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0084_rename_solde_achatsupport_prix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitebuilder',
            name='date_build',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
