# Generated by Django 5.0.4 on 2024-06-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0086_remove_locationwebsitebuilder_statu_du_website_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitebuilder',
            name='date_fin_hebergement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitebuilder',
            name='date_hebergement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
