# Generated by Django 5.0.4 on 2024-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0087_websitebuilder_date_fin_hebergement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationwebsitebuilder',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationwebsitebuilder',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
