# Generated by Django 5.0.4 on 2024-06-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0088_locationwebsitebuilder_date_debut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationwebsitebuilder',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='locationwebsitebuilder',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='locationwebsites',
            name='date_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationwebsites',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
