# Generated by Django 5.0.4 on 2024-06-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0089_remove_locationwebsitebuilder_date_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='CMS',
            field=models.CharField(choices=[('WordPress', 'WordPress'), ('Drupal', 'Drupal')], default='WordPress', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='catégorie',
            field=models.CharField(choices=[('Ecommerce', 'Ecommerce'), ('Blogs', 'Blogs'), ('Business', 'Business'), ('portfolio', 'portfolio'), ('Educational', 'Educational'), ('News', 'News')], default='Ecommerce', max_length=50, null=True),
        ),
    ]
