# Generated by Django 5.0.4 on 2024-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0092_websites_hebergement_payment_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='prix_hebergement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
