# Generated by Django 5.0.4 on 2024-07-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0094_getfreewebsites'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetFreeWebsiteBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_port', models.CharField(blank=True, max_length=30, null=True)),
                ('app_port', models.CharField(blank=True, max_length=30, null=True)),
                ('nameWebsite', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=50, null=True)),
                ('Statu_du_website', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=50, null=True)),
                ('date_build', models.DateTimeField(blank=True, null=True)),
                ('date_hebergement', models.DateTimeField(blank=True, null=True)),
                ('date_fin_hebergement', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('getfree_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsites')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites')),
            ],
        ),
    ]
