# Generated by Django 5.0.4 on 2024-07-02 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0095_getfreewebsitebuilder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedwebsitebuilder',
            name='getfree_website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
        migrations.AddField(
            model_name='websites_client_statu',
            name='getfree_website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
    ]
