# Generated by Django 5.0.4 on 2024-07-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0096_mergedwebsitebuilder_getfree_website_builder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_need_reset',
            name='getfree_website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
        migrations.AddField(
            model_name='website_need_suspendre',
            name='getfree_website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
        migrations.AddField(
            model_name='website_reprendre_suspendre',
            name='getfree_website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
        migrations.AddField(
            model_name='websites_need_delete',
            name='getfree_website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
    ]
