# Generated by Django 5.0.4 on 2024-07-03 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0097_website_need_reset_getfree_website_builder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites_hebergement_payment_delay',
            name='getfree_website_builder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
    ]
