# Generated by Django 5.0.4 on 2024-07-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0098_websites_hebergement_payment_delay_getfree_website_builder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_facturation', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('achat_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.achatsupport')),
                ('achat_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.achatwebsites')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('getfree_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsites')),
                ('location_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.locationwebsites')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.supports')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites')),
            ],
        ),
    ]
