# Generated by Django 5.0.4 on 2024-07-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0099_facturations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturations',
            name='achat_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.achatwebsites'),
        ),
        migrations.AlterField(
            model_name='facturations',
            name='getfree_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsites'),
        ),
        migrations.AlterField(
            model_name='facturations',
            name='location_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.locationwebsites'),
        ),
    ]
