# Generated by Django 5.0.4 on 2024-07-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0102_websites_hebergement_payment_reprendre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
