# Generated by Django 5.0.4 on 2024-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0105_delete_nona'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='piècejoint',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
