# Generated by Django 5.0.4 on 2024-07-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0107_remove_ticket_title_ticket_code_demande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('En Cours de traitement', 'En Cours de traitement'), ('Fermée', 'Fermée')], default='Open', max_length=40),
        ),
    ]
