# Generated by Django 5.0.4 on 2024-07-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0108_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Ouvert', 'Ouvert'), ('En Cours de traitement', 'En Cours de traitement'), ('Fermée', 'Fermée')], default='Ouvert', max_length=40),
        ),
    ]
