# Generated by Django 5.0.7 on 2024-07-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0112_ticket_updated_by_gc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='piècejoint',
            new_name='pièce_joint',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='piècejoint_updated_by',
            new_name='pièce_joint_updated_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='code_Demande',
        ),
        migrations.AddField(
            model_name='ticket',
            name='code_Ticket',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
