# Generated by Django 5.0.7 on 2024-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0113_rename_piècejoint_ticket_pièce_joint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code_Demande',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
