# Generated by Django 5.0.7 on 2024-07-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0116_alter_cliente_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
