# Generated by Django 5.0.7 on 2024-07-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0118_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En Cours de traitement', 'En Cours de traitement'), ('Fermée', 'Fermée')], default='Ouvert', max_length=40)),
                ('typeTicket', models.CharField(max_length=40)),
                ('Branche', models.CharField(max_length=40)),
                ('code_Ticket', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('nameSupport', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('code_Demande', models.CharField(blank=True, max_length=100, null=True)),
                ('description_updated_by', models.TextField(blank=True, max_length=2000, null=True)),
                ('pièce_joint_updated_by', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pièce_joint', models.ImageField(null=True, upload_to='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('updated_by_gc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitebuilder.gestionnairecomptes')),
                ('updated_by_ts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='websitebuilder.supporttechnique')),
                ('websiteName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites')),
            ],
        ),
    ]
