# Generated by Django 5.0.7 on 2024-07-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0119_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='nameSupport',
        ),
        migrations.AddField(
            model_name='ticket',
            name='SupportName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.supports'),
        ),
    ]
