# Generated by Django 5.0.7 on 2024-07-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0120_remove_ticket_namesupport_ticket_supportname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='SupportName',
            new_name='supportName',
        ),
    ]
