# Generated by Django 5.0.7 on 2024-07-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0122_conversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
