# Generated by Django 5.0.7 on 2024-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0124_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_images/'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
