# Generated by Django 5.0.7 on 2024-07-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0125_conversation_image_alter_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='sender_type',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('SupportTechnique', 'SupportTechnique'), ('GestionnaireComptes', 'GestionnaireComptes')], max_length=20),
        ),
    ]
