# Generated by Django 5.0.7 on 2024-08-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0126_alter_conversation_sender_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Websites_location_payment_delay', 'Websites Location Payment Delay'), ('Websites_location_payment_reprendre', 'Websites Location Payment Reprendre'), ('Websites_Need_Delete', 'Websites Need Delete'), ('Website_need_resiliation', 'Website Need Resiliation'), ('Website_reprendre_resiliation', 'Website Reprendre Resiliation'), ('Website_need_suspendre', 'Website Need Suspendre'), ('Website_reprendre_suspendre', 'Website Reprendre Suspendre'), ('website_need_reset', 'Website Need Reset'), ('Websites_hebergement_payment_delay', 'Websites Hebergement Payment Delay'), ('Websites_hebergement_payment_reprendre', 'Websites Hebergement Payment Reprendre')], max_length=50)),
                ('instance_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.cliente')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websites')),
            ],
        ),
    ]
