# Generated by Django 5.0.7 on 2024-08-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0127_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='getfree_website_builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.getfreewebsitebuilder'),
        ),
        migrations.AddField(
            model_name='history',
            name='location_website_builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.locationwebsitebuilder'),
        ),
        migrations.AddField(
            model_name='history',
            name='website_builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='websitebuilder.websitebuilder'),
        ),
    ]
