# Generated by Django 5.0.7 on 2025-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0131_adminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
