# Generated by Django 5.0.7 on 2025-08-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0133_gestionnairecomptes_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionnairecomptes',
            name='created_by',
        ),
    ]
