# Generated by Django 5.0.7 on 2025-08-31 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitebuilder', '0133_historiqueaction'),
        ('websitebuilder', '0134_remove_gestionnairecomptes_created_by'),
    ]

    operations = [
    ]
